// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDtUHfziuj8XlbW2P91B4ljB-3Y4gKjzU',
    appId: '1:124781148977:web:4a1e0f0b88f623ded58e10',
    messagingSenderId: '124781148977',
    projectId: 'splashscreen-35417',
    authDomain: 'splashscreen-35417.firebaseapp.com',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    measurementId: 'G-SDTERTL1PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC4dEBh6zgO0BI1kLe8rfKWWpJZ3Ac7wU',
    appId: '1:124781148977:android:7fada2ecf6a7457fd58e10',
    messagingSenderId: '124781148977',
    projectId: 'splashscreen-35417',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJ2T_XQcX8SMLXojSbfhocxwJ8NqYVsg',
    appId: '1:124781148977:ios:f399e3afbffc7785d58e10',
    messagingSenderId: '124781148977',
    projectId: 'splashscreen-35417',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    iosBundleId: 'com.example.splashscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJ2T_XQcX8SMLXojSbfhocxwJ8NqYVsg',
    appId: '1:124781148977:ios:f399e3afbffc7785d58e10',
    messagingSenderId: '124781148977',
    projectId: 'splashscreen-35417',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    iosBundleId: 'com.example.splashscreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDtUHfziuj8XlbW2P91B4ljB-3Y4gKjzU',
    appId: '1:124781148977:web:3f8acd3ba948f6e5d58e10',
    messagingSenderId: '124781148977',
    projectId: 'splashscreen-35417',
    authDomain: 'splashscreen-35417.firebaseapp.com',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    measurementId: 'G-74TFNE428B',
  );
}
