// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api',
    appId:'your id',
    messagingSenderId: 'id',
    projectId: 'splashscreen-35417',
    authDomain: 'splashscreen-35417.firebaseapp.com',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    measurementId: 'G-SDTERTL1PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:'your api key',
    appId: 'id',
    messagingSenderId: 'id',
    projectId: 'splashscreen-35417',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'q_YOUR_API',
    appId: '_YOUR_ID',
    messagingSenderId: 'id',
    projectId: 'splashscreen-35417',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    iosBundleId: 'com.example.splashscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your api',
    appId: 'your id',
    messagingSenderId: 'id',
    projectId: 'splashscreen-35417',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    iosBundleId: 'com.example.splashscreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your api'
    appId: 'id',
    messagingSenderId: 'id',
    projectId: 'splashscreen-35417',
    authDomain: 'splashscreen-35417.firebaseapp.com',
    storageBucket: 'splashscreen-35417.firebasestorage.app',
    measurementId: 'G-74TFNE428B',
  );
}
